In [1]:
import numpy as np
import pandas as pd 
from tqdm import tqdm
import pandas as pd
tqdm.pandas(desc='pandas bar')
# from pandarallel import pandarallel
import random
from tqdm.notebook import tqdm
import copy
import logging
# pandarallel.initialize(progress_bar=True)

import argparse
from types import SimpleNamespace
from ditto.model import DittoModel,DittoDataset,load_model,to_str,classify,train,simple_train,simple_train_update
import os

In [1]:
from utils.load_dataset import DatasetLoader,GSLDataset

## Set for CUDA_VISIBLE_DEVICES, only single card is supported

In [2]:
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
os.environ["TOKENIZERS_PARALLELISM"] = "false"

## Training args

In [3]:
from sklearn.metrics import f1_score
hp_simple = SimpleNamespace(task='hospital-detector-train',
                     batch_size=64,
                     max_len=128,
                     lr=3e-5,
                     n_epochs=20,
                     save_model=False,
                     logdir="detector_model/", ## Checkpoint save path
                     lm='/home/yanmy/roberta-base', ## roberta-base model, please change to your own model path
                     fp16=True,
                     alpha_aug=0.8)

##### Load Training/Inferencing data

dataloader takes 3-column (text0-text1-label) DataFrame as input

replace `dataset` to your target dataset

In [1]:
# main_script.py (或者其他需要进行聚类的地方)

import numpy as np
import pandas as pd # 如果你需要模拟 dirty_table
from utils.clustering import KMeansClusterer

# --- 1. 准备你的嵌入数据和聚类数量 ---

# 假设 triple_embedding 是你的嵌入矩阵
# 实际场景中，这会是你从 GraphTrainer 或 SemanticEmbedder 得到的输出
num_samples = 1000
embedding_dim = 1024
example_embedding = np.random.rand(num_samples, embedding_dim) # 模拟嵌入数据

cluster_division_number = 10 # 你想要的聚类数量

# --- 2. 实例化 KMeansClusterer ---
# 可以设置 random_state 来确保聚类结果的可复现性
clusterer = KMeansClusterer(n_clusters=cluster_division_number, random_state=42)

In [1]:
from openai import OpenAI
client = OpenAI(
    base_url="http://192.168.12.43:8000/v1",
    api_key='token-example',
)

In [5]:
completion = client.chat.completions.create(
    model = '/data/home/wangys/model/Qwen2.5-Coder-7B',
    messages=[
    
    {"role": "user", "content": 'Write a sudoku game demo for me'}
    ],
    # extra_body={
    #   "guided_choice": ["positive", "negative"]
    # }
)
detector_func = completion.choices[0].message.content

In [6]:
print(detector_func)

Sure! Below is a simple Sudoku game demo in Python using the Pygame library. This demo will allow you to play Sudoku on your computer.

First, make sure you have Pygame installed. If not, you can install it using pip:

```sh
pip install pygame
```

Now, here's the code for the Sudoku game demo:

```python
import pygame
import random

# Initialize Pygame
pygame.init()

# Constants
WIDTH, HEIGHT = 540, 600
GRID_SIZE = 9
CELL_SIZE = WIDTH // GRID_SIZE
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
GREEN = (0, 255, 0)

# Create the display
screen = pygame.display.set_mode((WIDTH, HEIGHT))
pygame.display.set_caption("Sudoku Game")

# Font
font = pygame.font.SysFont(None, 36)

# Generate a new Sudoku puzzle
def generate_sudoku():
    def is_valid(board, row, col, num):
        for x in range(9):
            if board[row][x] == num or board[x][col] == num:
                return False

        start_row, start_col = 3 * (row // 3), 3 * (col // 3)
        for i in range(3):
            for j in range(3):
                if board[i + start_row][j + start_col] == num:
                    return False

        return True

    def solve_sudoku(board):
        empty = find_empty(board)
        if not empty:
            return True
        else:
            row, col = empty

        for num in range(1, 10):
            if is_valid(board, row, col, num):
                board[row][col] = num

                if solve_sudoku(board):
                    return True

                board[row][col] = 0

        return False

    def find_empty(board):
        for i in range(len(board)):
            for j in range(len(board[0])):
                if board[i][j] == 0:
                    return (i, j)
        return None

    board = [[0 for _ in range(GRID_SIZE)] for _ in range(GRID_SIZE)]
    solve_sudoku(board)

    # Remove numbers to create a puzzle
    num_to_remove = 40
    while num_to_remove > 0:
        row = random.randint(0, GRID_SIZE - 1)
        col = random.randint(0, GRID_SIZE - 1)
        if board[row][col] != 0:
            board[row][col] = 0
            num_to_remove -= 1

    return board

# Draw the Sudoku grid
def draw_grid(board):
    for i in range(GRID_SIZE + 1):
        thickness = 4 if i % 3 == 0 else 1
        pygame.draw.line(screen, BLACK, (i * CELL_SIZE, 0), (i * CELL_SIZE, HEIGHT), thickness)
        pygame.draw.line(screen, BLACK, (0, i * CELL_SIZE), (WIDTH, i * CELL_SIZE), thickness)

# Draw the numbers on the Sudoku grid
def draw_numbers(board):
    for row in range(GRID_SIZE):
        for col in range(GRID_SIZE):
            if board[row][col] != 0:
                text = font.render(str(board[row][col]), True, BLACK)
                screen.blit(text, ((col + 0.5) * CELL_SIZE - text.get_width() / 2, (row + 0.5) * CELL_SIZE - text.get_height() / 2))

# Main game loop
def main():
    board = generate_sudoku()
    selected_cell = None
    input_number = None

    running = True
    while running:
        screen.fill(WHITE)
        draw_grid(board)
        draw_numbers(board)

        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False
            elif event.type == pygame.MOUSEBUTTONDOWN:
                mouse_pos = pygame.mouse.get_pos()
                row = mouse_pos[1] // CELL_SIZE
                col = mouse_pos[0] // CELL_SIZE
                selected_cell = (row, col)
            elif event.type == pygame.KEYDOWN:
                if selected_cell and '1' <= event.unicode <= '9':
                    input_number = int(event.unicode)
                elif event.key == pygame.K_BACKSPACE or event.key == pygame.K_DELETE:
                    input_number = None

        if selected_cell and input_number is not None and board[selected_cell[0]][selected_cell[1]] == 0:
            board[selected_cell[0]][selected_cell[1]] = input_number
            input_number = None

        pygame.display.flip()

    pygame.quit()

if __name__ == "__main__":
    main()
```

This code sets up a basic Sudoku game where you can click on cells to select them and type numbers to fill them in. The `generate_sudoku` function creates a new Sudoku puzzle by solving an empty board and then removing some numbers to create a solvable puzzle.

To run the game, save the code to a file (e.g., `sudoku.py`) and run it with Python:

```sh
python sudoku.py
```

Enjoy playing Sudoku!

In [ ]:

# --- 3. 调用 perform_clustering 方法 ---
# 传入你的嵌入数据

# --- 4. 打印结果 (示例) ---
print(f"\nK-Means 聚类结果:")
for cluster_id, info in resulting_clusters.items():
    print(f"\n--- 聚类 {cluster_id} ---")
    print(f"成员数量: {len(info['members'])}")
    if info['members']: # Check if the cluster is not empty
        print(f"质心形状: {info['centroid'].shape}")
        print(f"离群点索引: {info['outlier_index']}")
        print(f"部分排序后的成员 (前5个，最远的在前): {info['members'][:5]}")
    else:
        print(f"聚类 {cluster_id} 为空。")

# 示例：访问特定聚类的信息
if 0 in resulting_clusters:
    cluster_0_members = resulting_clusters[0]['members']
    cluster_0_centroid = resulting_clusters[0]['centroid']
    cluster_0_outlier = resulting_clusters[0]['outlier_index']
    
    print(f"\n聚类 0 的成员数量: {len(cluster_0_members)}")
    if cluster_0_outlier is not None:
        print(f"聚类 0 的离群点索引: {cluster_0_outlier}")

In [1]:
from ditto.model import DittoModel,DittoDataset,load_model,to_str,classify,train,simple_train,simple_train_update

In [23]:
train_output = pd.read_csv('GEIL_Data/imdb/detector/train.csv',index_col=0).astype(str)

valid_output = pd.read_csv('GEIL_Data/imdb/detector/train.csv',index_col=0).astype(str)

test_output = pd.read_csv('GEIL_Data/imdb/detector/test.csv',index_col=0).astype(str)
train_dataset = DittoDataset(train_output,max_len=128,lm = '/home/yanmy/roberta-base')
valid_dataset = DittoDataset(valid_output,max_len=128,lm = '/home/yanmy/roberta-base')
test_dataset = DittoDataset(test_output.sample(n=1000),max_len=128,lm = '/home/yanmy/roberta-base')
test_dataset_all = DittoDataset(test_output,max_len=128,lm = '/home/yanmy/roberta-base')

FileNotFoundError: [Errno 2] No such file or directory: 'GEIL_Data/imdb/detector/test.csv'

In [25]:
train_output

,0,1,2
0,COL titleType VAL tvSpxcial COL title VAL Wres...,COL titleType VAL tvSpxcial,1
1,COL titleType VAL tvSpecial COL title VAL Wres...,COL titleType VAL tvSpecial,0
2,COL titleType VAL tvSpecial COL title VAL Wres...,COL title VAL WresxleMania XV,1
3,COL titleType VAL tvSpecial COL title VAL Wres...,COL title VAL WrestleMania XV,0
4,COL titleType VAL tvSpecial COL title VAL Wres...,COL runtimeMinutes VAL 2.77 h,1
...,...,...,...
428019,COL titleType VAL movie COL title VAL Chx Chx ...,COL startYear VAL 2019,0
428020,COL titleType VAL movie COL title VAL Chx Chx ...,COL runtimeMinutes VAL 1.7 h,1
428021,COL titleType VAL movie COL title VAL Chx Chx ...,COL runtimeMinutes VAL 104,0
428022,COL titleType VAL movie COL title VAL Chx Chx ...,COL director VAL Kathỹ Uyen,1
428023,COL titleType VAL movie COL title VAL Chx Chx ...,COL director VAL Kathy Uyen,0

:

In [20]:
hp_simple.n_epochs = 10
model_output = simple_train(train_dataset,valid_dataset,test_dataset,hp_simple) ## Training
import time
from sklearn.metrics import precision_score,recall_score,f1_score
start_time = time.time()
predict = classify(test_dataset_all,model=model_output,lm='/home/yanmy/roberta-base',max_len=128,threshold=0.5) ## Inference
# result_f1 = f1_score(y_pred=predict[0],y_true=test_all.iloc[:,-1].astype(int))
# print('episode_%s Task: %s f1-score: %s' % ('0','rayyan-init-20',str(result_f1)))
end_time = time.time()
print(f"inference time：{end_time - start_time} s")
print("prec: ", precision_score(y_pred=predict[0],y_true=test_output.iloc[:,-1].astype(int)), " recall: ",  recall_score(y_pred=predict[0],y_true=test_output.iloc[:,-1].astype(int)), ", f1: ", f1_score(y_pred=predict[0],y_true=test_output.iloc[:,-1].astype(int)))

LM Model 2

/home/yanmy/anaconda3/envs/punica/lib/python3.11/site-packages/transformers/optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
/home/yanmy/anaconda3/envs/punica/lib/python3.11/site-packages/apex/amp/_initialize.py:25: UserWarning: An input tensor was not cuda.
  warnings.warn("An input tensor was not cuda.")

Selected optimization level O2:  FP16 training with FP32 batchnorm and FP32 master weights.

Defaults for this optimization level are:
enabled                : True
opt_level              : O2
cast_model_type        : torch.float16
patch_torch_functions  : False
keep_batchnorm_fp32    : True
master_weights         : True
loss_scale             : dynamic
Processing user overrides (additional kwargs that are not None)...
After processing overrides, optimization options are:
enabled                : True
opt_level              : O2
cast_model_type        : torch.float16
patch_torch_functions  : False
keep_batchnorm_fp32    : True
master_weights         : True
loss_scale             : dynamic
Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 32768.0
step: 0, loss: 0.7205385565757751
Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 16384.0
step: 50, loss: 0.012252089567482471
step: 100, loss: 0.00016557039634790272

/home/yanmy/anaconda3/envs/punica/lib/python3.11/site-packages/apex/amp/_initialize.py:25: UserWarning: An input tensor was not cuda.
  warnings.warn("An input tensor was not cuda.")

epoch 1: dev_f1=1.0, f1=0.7666666666666667, best_f1=0.7666666666666667
21.791600704193115
step: 0, loss: 0.0001353641418972984

/home/yanmy/anaconda3/envs/punica/lib/python3.11/site-packages/apex/amp/_initialize.py:25: UserWarning: An input tensor was not cuda.
  warnings.warn("An input tensor was not cuda.")

Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 8192.0
step: 50, loss: 0.01787702552974224
Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 4096.0
step: 100, loss: 0.001591160660609603

/home/yanmy/anaconda3/envs/punica/lib/python3.11/site-packages/apex/amp/_initialize.py:25: UserWarning: An input tensor was not cuda.
  warnings.warn("An input tensor was not cuda.")

epoch 2: dev_f1=1.0, f1=0.7666666666666667, best_f1=0.7666666666666667
21.5860333442688
step: 0, loss: 0.00040936708683148026

/home/yanmy/anaconda3/envs/punica/lib/python3.11/site-packages/apex/amp/_initialize.py:25: UserWarning: An input tensor was not cuda.
  warnings.warn("An input tensor was not cuda.")

step: 50, loss: 0.00021358471713028848
step: 100, loss: 0.00016087995027191937

/home/yanmy/anaconda3/envs/punica/lib/python3.11/site-packages/apex/amp/_initialize.py:25: UserWarning: An input tensor was not cuda.
  warnings.warn("An input tensor was not cuda.")

epoch 3: dev_f1=1.0, f1=0.7666666666666667, best_f1=0.7666666666666667
21.934019088745117
step: 0, loss: 0.0001295265246881172

/home/yanmy/anaconda3/envs/punica/lib/python3.11/site-packages/apex/amp/_initialize.py:25: UserWarning: An input tensor was not cuda.
  warnings.warn("An input tensor was not cuda.")

step: 50, loss: 0.00012579916801769286
step: 100, loss: 0.00010874067811528221

/home/yanmy/anaconda3/envs/punica/lib/python3.11/site-packages/apex/amp/_initialize.py:25: UserWarning: An input tensor was not cuda.
  warnings.warn("An input tensor was not cuda.")

epoch 4: dev_f1=1.0, f1=0.7666666666666667, best_f1=0.7666666666666667
21.80031991004944
step: 0, loss: 8.591309597250074e-05

/home/yanmy/anaconda3/envs/punica/lib/python3.11/site-packages/apex/amp/_initialize.py:25: UserWarning: An input tensor was not cuda.
  warnings.warn("An input tensor was not cuda.")

step: 50, loss: 8.299640467157587e-05
step: 100, loss: 6.703127291984856e-05

/home/yanmy/anaconda3/envs/punica/lib/python3.11/site-packages/apex/amp/_initialize.py:25: UserWarning: An input tensor was not cuda.
  warnings.warn("An input tensor was not cuda.")

epoch 5: dev_f1=1.0, f1=0.7666666666666667, best_f1=0.7666666666666667
21.978588819503784
step: 0, loss: 7.787581125739962e-05

/home/yanmy/anaconda3/envs/punica/lib/python3.11/site-packages/apex/amp/_initialize.py:25: UserWarning: An input tensor was not cuda.
  warnings.warn("An input tensor was not cuda.")

step: 50, loss: 7.06626960891299e-05
step: 100, loss: 5.24653478350956e-05

/home/yanmy/anaconda3/envs/punica/lib/python3.11/site-packages/apex/amp/_initialize.py:25: UserWarning: An input tensor was not cuda.
  warnings.warn("An input tensor was not cuda.")

epoch 6: dev_f1=1.0, f1=0.7666666666666667, best_f1=0.7666666666666667
22.13148522377014
step: 0, loss: 6.005423711030744e-05

/home/yanmy/anaconda3/envs/punica/lib/python3.11/site-packages/apex/amp/_initialize.py:25: UserWarning: An input tensor was not cuda.
  warnings.warn("An input tensor was not cuda.")

step: 50, loss: 5.19400455232244e-05
step: 100, loss: 5.304435399011709e-05

/home/yanmy/anaconda3/envs/punica/lib/python3.11/site-packages/apex/amp/_initialize.py:25: UserWarning: An input tensor was not cuda.
  warnings.warn("An input tensor was not cuda.")

epoch 7: dev_f1=1.0, f1=0.7666666666666667, best_f1=0.7666666666666667
21.90499997138977
step: 0, loss: 4.741204611491412e-05

/home/yanmy/anaconda3/envs/punica/lib/python3.11/site-packages/apex/amp/_initialize.py:25: UserWarning: An input tensor was not cuda.
  warnings.warn("An input tensor was not cuda.")

step: 50, loss: 5.155601684236899e-05
step: 100, loss: 4.8791884182719514e-05

/home/yanmy/anaconda3/envs/punica/lib/python3.11/site-packages/apex/amp/_initialize.py:25: UserWarning: An input tensor was not cuda.
  warnings.warn("An input tensor was not cuda.")

epoch 8: dev_f1=1.0, f1=0.7666666666666667, best_f1=0.7666666666666667
21.90964698791504
step: 0, loss: 4.4009200792061165e-05

/home/yanmy/anaconda3/envs/punica/lib/python3.11/site-packages/apex/amp/_initialize.py:25: UserWarning: An input tensor was not cuda.
  warnings.warn("An input tensor was not cuda.")

step: 50, loss: 4.091384107596241e-05
step: 100, loss: 5.310752021614462e-05

/home/yanmy/anaconda3/envs/punica/lib/python3.11/site-packages/apex/amp/_initialize.py:25: UserWarning: An input tensor was not cuda.
  warnings.warn("An input tensor was not cuda.")

epoch 9: dev_f1=1.0, f1=0.7666666666666667, best_f1=0.7666666666666667
21.946917295455933
step: 0, loss: 3.930821185349487e-05

/home/yanmy/anaconda3/envs/punica/lib/python3.11/site-packages/apex/amp/_initialize.py:25: UserWarning: An input tensor was not cuda.
  warnings.warn("An input tensor was not cuda.")

step: 50, loss: 4.170710235484876e-05
step: 100, loss: 4.26272745244205e-05

/home/yanmy/anaconda3/envs/punica/lib/python3.11/site-packages/apex/amp/_initialize.py:25: UserWarning: An input tensor was not cuda.
  warnings.warn("An input tensor was not cuda.")

epoch 10: dev_f1=1.0, f1=0.7666666666666667, best_f1=0.7666666666666667
22.089617013931274

/home/yanmy/anaconda3/envs/punica/lib/python3.11/site-packages/apex/amp/_initialize.py:25: UserWarning: An input tensor was not cuda.
  warnings.warn("An input tensor was not cuda.")

inference time：28.61542820930481 s
prec:  0.9994340690435767  recall:  0.5954146999325691 , f1:  0.7462497358968941

In [22]:
pd.read_csv('GEIL_Data/tax/original/clean.csv')

,f_name,l_name,gender,area_code,phone,city,state,zip,marital_status,has_child,salary,rate,single_exemp,married_exemp,child_exemp
0,Pengyuan,Zendler,F,508,744-9007,SWAMPSCOTT,MA,1907,M,N,90000,5.300000,0,7150,0
1,Nik,Tacic,M,702,517-7658,LAS VEGAS,NV,89140,M,N,90000,0.000000,0,0,0
2,Hovav,Punter,M,501,304-9763,HASTY,AR,72640,S,N,50000,7.000000,20,0,0
3,Xiangning,Vanneste,F,862,651-6469,BRIGANTINE,NJ,8203,M,Y,55000,1.951979,0,2000,1500
4,Belen,Niccum,F,920,287-1889,FLORENCE,WI,54121,S,Y,85000,5.923291,700,0,400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199995,Galeno,Abels,F,850,807-1573,MILTON,FL,32570,S,N,60000,0.000000,0,0,0
199996,Ahmadreza,Scherl,F,971,491-3046,SCOTTS MILLS,OR,97375,M,N,45000,9.000000,0,318,0
199997,Assef,Aba,M,857,147-4697,FRAMINGHAM,MA,1704,S,N,85000,5.300000,3575,0,0
199998,Neri,Walpole,F,865,592-8528,NASHVILLE,TN,37248,M,N,15000,0.000000,0,0,0
199999,Christoforos,Smagt,M,406,961-2205,GILDFORD,MT,59525,S,Y,75000,6.900000,1900,0,1900

In [21]:
len(test_dataset_all)

43935

In [6]:
print("prec: ", precision_score(y_pred=predict[0],y_true=test_output.iloc[:,-1].astype(int)), " recall: ",  recall_score(y_pred=predict[0],y_true=test_output.iloc[:,-1].astype(int)), ", f1: ", f1_score(y_pred=predict[0],y_true=test_output.iloc[:,-1].astype(int)))

prec:  0.9438202247191011  recall:  0.9901768172888016 , f1:  0.9664429530201343

##### For result to detector
- the predict result is 1-d array, you should reshape to (row_num,-1) to fit for dirty.csv shape
- `beers` dataset, we omit the first 2 columns
- `rayyan` dataset, we omit the first 1 columns
-

In [ ]:
result = np.array(predict[0]).reshape((-1,6)) ## reshape to match the dirty.csv shape


np.save('GEIL_Data/dataset/detector/detector.npy',result)